/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4a6da9ffb595e182f0a025599f450adb)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}