//! COW Shed factory ABI bindings.
//!
//! Re-export of the [`COWShedFactory`] interface generated by the
//! canonical `eip712::sol_types` sol! block. The
//! [`COWShedFactoryEns`] forwarder is feature-gated and lives in a
//! dedicated sol! block here because it does not reference the canonical
//! `Call` struct.

pub use crate::eip712::sol_types::COWShedFactory;

#[cfg(feature = "cow-shed-ens")]
use alloy_sol_types::sol;

#[cfg(feature = "cow-shed-ens")]
sol! {
    /// ENS-oriented factory ABI extension.
    interface COWShedFactoryEns {
        /// Forward ENS node resolution.
        function addr(bytes32 node) external view returns (address);
        /// Base ENS name.
        function baseName() external view returns (string);
        /// Base ENS node.
        function baseNode() external view returns (bytes32);
        /// Forward resolution node.
        function forwardResolutionNodeToAddress(bytes32 node) external view returns (address);
        /// Initialize ENS records for a user.
        function initializeEns(address user) external;
        /// Reverse ENS node name.
        function name(bytes32 node) external view returns (string);
        /// Reverse resolution node.
        function reverseResolutionNodeToAddress(bytes32 node) external view returns (address);
        /// ERC-165 support query.
        function supportsInterface(bytes4 interfaceId) external pure returns (bool);
    }
}
