//! COW Shed proxy ABI bindings.
//!
//! Re-export of the [`COWShed`](crate::eip712::sol_types::COWShed)
//! interface generated by the canonical
//! [`crate::eip712::sol_types`] sol! block. The proxy interface, the
//! factory interface, and the EIP-712 typed-data structs are declared in
//! one macro scope so every `Call[]`-bearing function signature
//! references the same generated `Call` type.

pub use crate::eip712::sol_types::COWShed;
